//user
export const USER_LOGIN_REQUEST= "USER_LOGIN_REQUEST/TIX"
export const USER_LOGIN_SUCCESS= "USER_LOGIN_SUCCESS/TIX"
export const USER_LOGIN_FAILED= "USER_LOGIN_FAILED/TIX"

export const SET_USER_LOGIN = "SET_USER_LOGIN"
export const GET_LIST_USER = "GET_LIST_USER"
export const GET_INFO_USER = "GET_INFO_USER"

export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST'
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS'
export const USER_SIGN_UP_FAILED = 'USER_SIGN_UP_FAILED'

export const RESET_LOAD_INFO_USER = "RESET_LOAD_INFO_USER"
export const RESET_BOOKING_ID = 'RESET_BOOKING_ID'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED'

//movie

export const GET_INFO_MOVIE_ITEM_REQUEST = 'GET_INFO_MOVIE_ITEM_REQUEST'
export const GET_INFO_MOVIE_ITEM_SUCCESS = 'GET_INFO_MOVIE_ITEM_SUCCESS'
export const GET_INFO_MOVIE_ITEM_FAILED = 'GET_INFO_MOVIE_ITEM_FAILED'


//cinema

export const GET_LIST_CINEMA_BY_MOVIE_ID = 'GET_LIST_THEATER_BY_MOVIE_ID'
export const LOGIN_BEFORE_BOOKING = 'LOGIN_BEFORE_BOOKING'
export const GET_LIST_CINEMA_API = 'GET_LIST_CINEMA_API'
export const GET_LIST_THEATERS_BY_ID = 'GET_LIST_THEATERS_BY_ID'
export const GET_SCHEDULE_BY_THEATERS_ID = 'GET_SCHEDULE_BY_THEATERS_ID'



