//user
export const USER_LOGIN_REQUEST= "USER_LOGIN_REQUEST/TIX"
export const USER_LOGIN_SUCCESS= "USER_LOGIN_SUCCESS/TIX"
export const USER_LOGIN_FAILED= "USER_LOGIN_FAILED/TIX"

export const SET_USER_LOGIN = "SET_USER_LOGIN"
export const GET_LIST_USER = "GET_LIST_USER"
export const GET_INFO_USER = "GET_INFO_USER"

export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST'
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS'
export const USER_SIGN_UP_FAILED = 'USER_SIGN_UP_FAILED'

export const RESET_LOAD_INFO_USER = "RESET_LOAD_INFO_USER"