export const GET_LIST_OF_SEAT_CINEMA_REQUEST ='GET_LIST_OF_SEAT_CINEMA_REQUEST '
export const GET_LIST_OF_SEAT_CINEMA_SUCCESS ='GET_LIST_OF_SEAT_CINEMA_SUCCESS '
export const GET_LIST_OF_SEAT_CINEMA_FAILED ='GET_LIST_OF_SEAT_CINEMA_FAILED '

export const RESET_LIST_TICKET_ROOM = 'RESET_LIST_TICKET_ROOM'
export const CHOOSE_SEAT = 'CHOOSE_SEAT'

export const UNCLICK_SEAT = 'UNCLICK_SEAT'

export const BOOKING_TICKET_API = 'BOOKING_TICKET_API'