export const GET_LIST_MOVIE_REQUEST = 'GET_LIST_MOVIE_REQUEST_PAGE'
export const GET_LIST_MOVIE_SUCCESS = 'GET_LIST_MOVIE_SUCCESS_PAGE'
export const GET_LIST_MOVIE_FAILED = 'GET_LIST_MOVIE_FAILED_PAGE'